"""add column translation

Revision ID: 67a109a609e8
Revises: 057c14580360
Create Date: 2025-01-09 06:13:13.609147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a109a609e8'
down_revision: Union[str, None] = '057c14580360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('translation', sa.String(), nullable=False))
    op.add_column('word', sa.Column('completed', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'translation')
    op.drop_column('word', 'completed')
    # ### end Alembic commands ###
